swagger: '2.0'
info:
  title: shipping
  x-ibm-name: shipping
  version: 2.1.0
  license:
    name: MIT
schemes:
  - https
basePath: /shipping
produces:
  - application/json
consumes:
  - application/json
security:
  - Client ID: []
    Client Secret: []
securityDefinitions:
  Client ID:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
    description: Client ID of your registered application.
  Client Secret:
    in: header
    name: X-IBM-Client-Secret
    type: apiKey
    description: Client Secret of your registered application.
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  gateway: datapower-api-gateway
  assembly:
    execute:
      - switch:
          version: 2.0.0
          title: switch
          case:
            - condition: ($operationPath() = '/calculate')
              execute:
                - invoke:
                    version: 2.0.0
                    title: invoke_fedex
                    timeout: 60
                    verb: GET
                    cache-response: protocol
                    cache-ttl: 900
                    target-url: >-
                      $(api.properties.shipping_svc_url)/shipping/calculate?company=fedex&from_zip=90210&to_zip={zip}
                    output: invoke_fedex_rsp
                    header-control:
                      type: blacklist
                      values: []
                    parameter-control:
                      type: blacklist
                      values: []
                - invoke:
                    title: invoke_ups
                    version: 2.0.0
                    timeout: 60
                    verb: GET
                    cache-response: protocol
                    cache-ttl: 900
                    description: ''
                    target-url: >-
                      $(api.properties.shipping_svc_url)/shipping/calculate?company=ups&from_zip=90210&to_zip={zip}
                    output: invoke_ups_rsp
                    header-control:
                      type: blacklist
                      values: []
                    parameter-control:
                      type: blacklist
                      values: []
                - map:
                    title: map_rsp
                    version: 2.0.0
                    inputs:
                      fedex_rates:
                        schema:
                          $schema: 'http://json-schema.org/draft-04/schema#'
                          id: 'http://jsonschema.net'
                          type: object
                          properties:
                            company:
                              id: 'http://jsonschema.net/company'
                              type: string
                              name: company
                            rates:
                              id: 'http://jsonschema.net/rates'
                              type: object
                              properties:
                                next_day:
                                  id: 'http://jsonschema.net/rates/next_day'
                                  type: string
                                  name: next_day
                                two_day:
                                  id: 'http://jsonschema.net/rates/two_day'
                                  type: string
                                  name: two_day
                                ground:
                                  id: 'http://jsonschema.net/rates/ground'
                                  type: string
                                  name: ground
                              name: rates
                          required:
                            - company
                            - rates
                          title: fedex_rates
                        variable: invoke_fedex_rsp.body
                        content: application/json
                      ups_rates:
                        schema:
                          $schema: 'http://json-schema.org/draft-04/schema#'
                          id: 'http://jsonschema.net'
                          type: object
                          properties:
                            company:
                              id: 'http://jsonschema.net/company'
                              type: string
                              name: company
                            rates:
                              id: 'http://jsonschema.net/rates'
                              type: object
                              properties:
                                next_day:
                                  id: 'http://jsonschema.net/rates/next_day'
                                  type: string
                                  name: next_day
                                two_day:
                                  id: 'http://jsonschema.net/rates/two_day'
                                  type: string
                                  name: two_day
                                ground:
                                  id: 'http://jsonschema.net/rates/ground'
                                  type: string
                                  name: ground
                              name: rates
                          required:
                            - company
                            - rates
                          title: ups_rates
                        variable: invoke_ups_rsp.body
                        content: application/json
                    outputs:
                      output:
                        schema:
                          $ref: '#/definitions/shipping'
                        variable: message.body
                        content: application/json
                    actions:
                      - set: output.fedex.next_day
                        from: fedex_rates.rates.next_day
                      - set: output.fedex.two_day
                        from: fedex_rates.rates.two_day
                      - set: output.fedex.ground
                        from: fedex_rates.rates.ground
                      - set: output.ups.next_day
                        from: ups_rates.rates.next_day
                      - set: output.ups.two_day
                        from: ups_rates.rates.two_day
                      - set: output.ups.ground
                        from: ups_rates.rates.ground
                    description: Combine shipping rates from FedEx and UPS
    catch:
      - errors:
          - ConnectionError
        execute: []
  properties:
    shipping_svc_url:
      value: 'https://funwithshipping.mybluemix.net'
      description: Server location for the LoopBack application
      encoded: false
  type: rest
  phase: realized
  catalogs: {}
  application-authentication:
    certificate: false
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
definitions:
  data_in:
    properties:
      data1:
        type: string
      data2:
        type: string
  shipping:
    properties:
      fedex:
        type: string
        $ref: '#/definitions/rates'
      ups:
        type: string
        $ref: '#/definitions/rates'
    required:
      - ups
      - fedex
  rates:
    properties:
      next_day:
        type: string
        example: '20.00'
      two_day:
        type: string
        example: '17.00'
      ground:
        type: string
        example: '8.00'
    required:
      - two_day
      - next_day
      - ground
paths:
  /calculate:
    get:
      responses:
        '200':
          description: 200 OK
          schema:
            $ref: '#/definitions/shipping'
      summary: Calculate shipping costs to a destination zip code
      operationId: shipping.calc
      parameters:
        - name: zip
          type: string
          required: true
          in: query
          description: Destination zip code.
      consumes:
        - application/json
      produces:
        - application/json
  /example/assembly:
    post:
      responses:
        '200':
          description: 200 OK
      operationId: example.assembly
      parameters:
        - name: data
          required: true
          in: body
          schema:
            $ref: '#/definitions/data_in'
